index:
    path: /
    controller: App\Controller\DefaultController::index

contact:
    path: /kontakt
    controller: App\Controller\DefaultController::contact

sitemap:
    path: /mapa
    controller: App\Controller\DefaultController::sitemap

send_mail:
    path: /wiadomosc_kontaktowa
    controller: App\Controller\DefaultController::mail

sitemap_xml:
    path: /sitemap.xml
    controller: App\Controller\SitemapController::xml

admin:
    path: /ck6mXWy7DM8X
    controller: App\Controller\AdminController::index

admin_projects:
    path: /ck6mXWy7DM8X/realizacje
    controller: App\Controller\AdminController::projects

admin_categories:
    path: /ck6mXWy7DM8X/kategorie
    controller: App\Controller\AdminController::categories

category:
    path: /{url}
    controller: App\Controller\DefaultController::category