index:
    path: /
    controller: App\Controller\DefaultController::index

contact:
    path: /kontakt
    controller: App\Controller\DefaultController::contact

category:
    path: /{url}
    controller: App\Controller\DefaultController::category