index:
    path: /
    controller: App\Controller\DefaultController::index

category:
    path: /{url}
    controller: App\Controller\DefaultController::category

subcategory:
    path: /{categoryUrl}/{url}
    controller: App\Controller\DefaultController::subcategory